#############################################################################
# Makefile for building: Test1
# Generated by qmake (2.01a) (Qt 4.8.1) on: Wed Apr 11 17:08:29 2012
# Project:  Test1.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile Test1.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -L/usr/local/lib -lntl -lblitz -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		exportdialog.cpp \
		parameter.cpp \
		warningdialog.cpp \
		errordialog.cpp \
		parset.cpp \
		ntl_ext.cpp \
		StepperBase.cpp \
		RHS_van.cpp moc_mainwindow.cpp \
		moc_exportdialog.cpp \
		moc_parameter.cpp \
		moc_warningdialog.cpp \
		moc_errordialog.cpp
OBJECTS       = main.o \
		mainwindow.o \
		exportdialog.o \
		parameter.o \
		warningdialog.o \
		errordialog.o \
		parset.o \
		ntl_ext.o \
		StepperBase.o \
		RHS_van.o \
		moc_mainwindow.o \
		moc_exportdialog.o \
		moc_parameter.o \
		moc_warningdialog.o \
		moc_errordialog.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Test1.pro
QMAKE_TARGET  = Test1
DESTDIR       = 
TARGET        = Test1

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_exportdialog.h ui_parameter.h ui_warningdialog.h ui_errordialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: Test1.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile Test1.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile Test1.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Test11.0.0 || $(MKDIR) .tmp/Test11.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Test11.0.0/ && $(COPY_FILE) --parents mainwindow.h exportdialog.h parameter.h warningdialog.h errordialog.h parset.h Odeint.h Output.h RHS_gyro.h StepperDopr853m.h ntl_ext.h StepperBase.h write_tec.h RuntimeException.h RHS_van.h .tmp/Test11.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp exportdialog.cpp parameter.cpp warningdialog.cpp errordialog.cpp parset.cpp ntl_ext.cpp StepperBase.cpp RHS_van.cpp .tmp/Test11.0.0/ && $(COPY_FILE) --parents mainwindow.ui exportdialog.ui parameter.ui warningdialog.ui errordialog.ui .tmp/Test11.0.0/ && (cd `dirname .tmp/Test11.0.0` && $(TAR) Test11.0.0.tar Test11.0.0 && $(COMPRESS) Test11.0.0.tar) && $(MOVE) `dirname .tmp/Test11.0.0`/Test11.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Test11.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_exportdialog.cpp moc_parameter.cpp moc_warningdialog.cpp moc_errordialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_exportdialog.cpp moc_parameter.cpp moc_warningdialog.cpp moc_errordialog.cpp
moc_mainwindow.cpp: parameter.h \
		parset.h \
		exportdialog.h \
		ui_mainwindow.h \
		Odeint.h \
		Output.h \
		RuntimeException.h \
		StepperDopr853m.h \
		ntl_ext.h \
		StepperBase.h \
		RHS_gyro.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_exportdialog.cpp: exportdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) exportdialog.h -o moc_exportdialog.cpp

moc_parameter.cpp: parset.h \
		parameter.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) parameter.h -o moc_parameter.cpp

moc_warningdialog.cpp: warningdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) warningdialog.h -o moc_warningdialog.cpp

moc_errordialog.cpp: errordialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) errordialog.h -o moc_errordialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_exportdialog.h ui_parameter.h ui_warningdialog.h ui_errordialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_exportdialog.h ui_parameter.h ui_warningdialog.h ui_errordialog.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_exportdialog.h: exportdialog.ui
	/usr/bin/uic-qt4 exportdialog.ui -o ui_exportdialog.h

ui_parameter.h: parameter.ui
	/usr/bin/uic-qt4 parameter.ui -o ui_parameter.h

ui_warningdialog.h: warningdialog.ui
	/usr/bin/uic-qt4 warningdialog.ui -o ui_warningdialog.h

ui_errordialog.h: errordialog.ui
	/usr/bin/uic-qt4 errordialog.ui -o ui_errordialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		parameter.h \
		parset.h \
		exportdialog.h \
		ui_mainwindow.h \
		Odeint.h \
		Output.h \
		RuntimeException.h \
		StepperDopr853m.h \
		ntl_ext.h \
		StepperBase.h \
		RHS_gyro.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		parameter.h \
		parset.h \
		exportdialog.h \
		ui_mainwindow.h \
		Odeint.h \
		Output.h \
		RuntimeException.h \
		StepperDopr853m.h \
		ntl_ext.h \
		StepperBase.h \
		RHS_gyro.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

exportdialog.o: exportdialog.cpp exportdialog.h \
		ui_exportdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exportdialog.o exportdialog.cpp

parameter.o: parameter.cpp parameter.h \
		parset.h \
		ui_parameter.h \
		warningdialog.h \
		errordialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parameter.o parameter.cpp

warningdialog.o: warningdialog.cpp warningdialog.h \
		ui_warningdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o warningdialog.o warningdialog.cpp

errordialog.o: errordialog.cpp errordialog.h \
		ui_errordialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o errordialog.o errordialog.cpp

parset.o: parset.cpp parset.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parset.o parset.cpp

ntl_ext.o: ntl_ext.cpp ntl_ext.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ntl_ext.o ntl_ext.cpp

StepperBase.o: StepperBase.cpp StepperBase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StepperBase.o StepperBase.cpp

RHS_van.o: RHS_van.cpp RHS_van.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RHS_van.o RHS_van.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_exportdialog.o: moc_exportdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_exportdialog.o moc_exportdialog.cpp

moc_parameter.o: moc_parameter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_parameter.o moc_parameter.cpp

moc_warningdialog.o: moc_warningdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_warningdialog.o moc_warningdialog.cpp

moc_errordialog.o: moc_errordialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_errordialog.o moc_errordialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

